spring.application.name=techtask

# 1. Configurações de Conexão com o Banco
spring.datasource.url=jdbc:mysql://localhost:3306/techtask
spring.datasource.username=root
spring.datasource.password=59784636

# 2. Configurações Mágicas do Hibernate (JPA)
# O "update" diz para o Spring: "Se a tabela não existir, crie. Se já existir, atualize."
spring.jpa.hibernate.ddl-auto=update

# 3. Mostrar os comandos SQL no console (Para a gente ver a mágica acontecendo)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

